"use client";

import { Download, Receipt } from "lucide-react";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { MOCK_INVOICE_LOGS } from "@/lib/admin-misc-mock";
import { cn } from "@/lib/utils";

const STATUS_STYLE = {
  paid: "bg-green-100 text-green-800",
  pending: "bg-orange-100 text-orange-800",
  overdue: "bg-red-100 text-red-800",
};

export default function InvoiceLogsPage() {
  const paid = MOCK_INVOICE_LOGS.filter((i) => i.status === "paid").length;
  const pending = MOCK_INVOICE_LOGS.filter((i) => i.status === "pending").length;

  return (
    <div className="space-y-6">
      <AdminPageHeader
        title="Invoice Logs"
        description="Invoices generated by plumbers via Plumber Guru tools"
      >
        <Button variant="outline" className="gap-2">
          <Download className="size-4" />
          Export CSV
        </Button>
      </AdminPageHeader>

      <div className="grid gap-4 sm:grid-cols-3">
        <Card className="py-4">
          <CardContent className="px-4 py-0">
            <p className="text-sm text-muted-foreground">Total invoices</p>
            <p className="text-2xl font-bold">{MOCK_INVOICE_LOGS.length}</p>
          </CardContent>
        </Card>
        <Card className="py-4">
          <CardContent className="px-4 py-0">
            <p className="text-sm text-muted-foreground">Paid</p>
            <p className="text-2xl font-bold text-green-600">{paid}</p>
          </CardContent>
        </Card>
        <Card className="py-4">
          <CardContent className="px-4 py-0">
            <p className="text-sm text-muted-foreground">Pending</p>
            <p className="text-2xl font-bold text-orange-600">{pending}</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Invoice ID</TableHead>
                <TableHead>Plumber</TableHead>
                <TableHead>Customer</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>GST</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {MOCK_INVOICE_LOGS.map((row) => (
                <TableRow key={row.id}>
                  <TableCell className="font-medium">
                    <span className="inline-flex items-center gap-2">
                      <Receipt className="size-4 text-primary" />
                      {row.id}
                    </span>
                  </TableCell>
                  <TableCell>{row.plumber}</TableCell>
                  <TableCell>{row.customer}</TableCell>
                  <TableCell>{row.amount}</TableCell>
                  <TableCell className="text-muted-foreground">
                    {row.gst}
                  </TableCell>
                  <TableCell className="text-sm">{row.date}</TableCell>
                  <TableCell>
                    <Badge
                      variant="secondary"
                      className={cn(STATUS_STYLE[row.status])}
                    >
                      {row.status}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
